name: Run Tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  flake8:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: python -m pip install --upgrade pip
      - run: pip install .
      - run: pip install flake8
      - run: flake8
  pytype:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: python -m pip install --upgrade pip
      - run: pip install .
      - run: pip install pytype
      - run: pytype .
